defaults: &defaults

  title: 'ふたりのウェディング'

  basePath: 'http://stage.2wed.jp/'

  login_type_names:
    'operation': '審査画面'
    'business': '管理画面'
    'average':  '一般ユーザー'

  user_status_names:
    'active':   '有効'
    'pennding': '停止中'

  user_type_names:
    'root':   'root'
    'master': 'マスター'
    'viewer': '閲覧者'
    'editor': '式場さま'
    'public': '一般'

  case_plan_type_names:
    - '-'
    - '挙式のみ'
    - '挙式+会食'
    - 'フォト+会食'

  case_prepare_type_names:
    - '-'
    - '1週間'
    - '2週間'
    - '3週間'
    - '4週間'
    - '1.0ヶ月'
    - '1.5ヶ月'
    - '2.0ヶ月'
    - '2.5ヶ月'
    - '3.0ヶ月'
    - '4.0ヶ月'
    - '5.0ヶ月'
    - '半年'
    - '一年'
    - '一年以上'

  delete: 
    - '未削除'
    - '削除済'

  corporation_admin_type_names:
    - '-'
    - '直営'
    - 'デスク運営'
    - '代理店'

  place_type_names:
    1: '総合結婚式場'
    2: 'ホテル'
    3: 'レストラン'
    4: 'ハウス'
    5: '教会'
    6: '神社仏閣'
    99: 'その他'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

