defaults: &defaults

  title: 'ふたりのウェディング'

  basePath: 'http://stage.2wed.jp/'

  login_type_names:
    'opration': '審査画面'
    'business': '管理画面'
    'average':  '一般ユーザー'

  user_status_names:
    'active':   '有効'
    'pennding': '停止中'

  user_type_names:
    'root':   'root'
    'master': 'マスター'
    'viewer': '閲覧者'
    'editor': '式場さま'
    'public': '一般'

  delete: 
    - '未削除'
    - '削除済'

  corporation_admin_type_names:
    - '-'
    - '直営'
    - 'デスク運営'
    - '代理店'

  place_type_names:
    1: '総合結婚式場'
    2: 'ホテル'
    3: 'レストラン'
    4: 'ハウス'
    5: '教会'
    6: '神社仏閣'
    99: 'その他'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

